import type {
  BlockType,
  EditorVersion,
  ParserCapability,
  ParserCapabilityId,
} from "./types.js"

export const getParserCapabilityId = ({
  editorVersion,
  blockType,
}: {
  editorVersion: EditorVersion
  blockType: BlockType
}): ParserCapabilityId => `se${editorVersion}-${blockType}`

const createCapability = ({
  editorVersion,
  blockType,
  fallbackPolicy,
  verificationMode,
  sampleIds,
}: Omit<ParserCapability, "id">): ParserCapability => ({
  id: getParserCapabilityId({
    editorVersion,
    blockType,
  }),
  editorVersion,
  blockType,
  fallbackPolicy,
  verificationMode,
  sampleIds,
})

export const parserCapabilities: ParserCapability[] = [
  createCapability({
    editorVersion: 2,
    blockType: "paragraph",
    fallbackPolicy: "best-effort",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-legacy", "se2-code-image-autolayout", "se2-table-rawhtml-navigation"],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "paragraph",
    fallbackPolicy: "best-effort",
    verificationMode: "sample-fixture",
    sampleIds: ["se3-legacy", "se3-quote-imagegroup-note9", "se3-quote-table-vita"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "paragraph",
    fallbackPolicy: "best-effort",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-formula-code-linkcard"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "heading",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "parser-fixture",
    sampleIds: [],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "heading",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-heading-itinerary"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "quote",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "parser-fixture",
    sampleIds: [],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "quote",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se3-quote-imagegroup-note9", "se3-quote-table-vita"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "quote",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-quote-formula-code"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "divider",
    fallbackPolicy: "structured",
    verificationMode: "parser-fixture",
    sampleIds: [],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "divider",
    fallbackPolicy: "structured",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-formula-code-linkcard", "se4-image-group"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "code",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-code-image-autolayout"],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "code",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "parser-fixture",
    sampleIds: [],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "code",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-formula-code-linkcard", "se4-quote-formula-code"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "formula",
    fallbackPolicy: "skip",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-formula-code-linkcard", "se4-quote-formula-code"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "image",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-code-image-autolayout", "se2-table-rawhtml-navigation"],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "image",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se3-quote-imagegroup-note9", "se3-quote-table-vita"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "image",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-video-table", "se4-image-legacy-link", "se4-quote-formula-code"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "imageGroup",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-thumburl-image-group"],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "imageGroup",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se3-quote-imagegroup-note9"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "imageGroup",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-image-group"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "video",
    fallbackPolicy: "skip",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-video-table"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "linkCard",
    fallbackPolicy: "markdown-paragraph",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-formula-code-linkcard", "se4-quote-formula-code"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "table",
    fallbackPolicy: "raw-html",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-table-rawhtml-navigation"],
  }),
  createCapability({
    editorVersion: 3,
    blockType: "table",
    fallbackPolicy: "raw-html",
    verificationMode: "sample-fixture",
    sampleIds: ["se3-quote-table-vita"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "table",
    fallbackPolicy: "raw-html",
    verificationMode: "sample-fixture",
    sampleIds: ["se4-video-table"],
  }),
  createCapability({
    editorVersion: 2,
    blockType: "rawHtml",
    fallbackPolicy: "raw-html",
    verificationMode: "sample-fixture",
    sampleIds: ["se2-table-rawhtml-navigation"],
  }),
  createCapability({
    editorVersion: 4,
    blockType: "rawHtml",
    fallbackPolicy: "raw-html",
    verificationMode: "parser-fixture",
    sampleIds: [],
  }),
]
